# Load the full R object

In [4]:
import rpy2.robjects as robjects
from rpy2.robjects import pandas2ri
import pandas as pd

In [1]:
pandas2ri.activate()

readRDS = robjects.r['readRDS']
r_obj = readRDS('data/UROMOL_TaLG.teachingcohort.rds')

# Extract the clinical data

In [2]:
# Drop 'exprs' column as before
colnames = list(r_obj.names)
clinical_cols = [name for name in colnames if name != 'exprs']
r_clinical = r_obj.rx(True, robjects.StrVector(clinical_cols))

# Convert to pandas
clinical_df = pandas2ri.rpy2py(r_clinical)
clinical_df

,UROMOL.ID,Progression,PFS_time.,Recurrence,RFS_time,FUtime_days.,Age,Sex,Smoking,Tumor.stage,Tumor.grade,Concomitant.CIS,Tumor.size,Incident.tumor,EAU.risk,BCG,UROMOL2021.classification
U0001,U0001,0,82.40,1,32.73,2472,86,M,Never,Ta,Low grade,No,< 3 cm,No,Intermediate,0,Class 1
U0002,U0002,0,72.10,1,4.97,2163,73,M,Former,Ta,Low grade,No,< 3 cm,No,Intermediate,0,Class 2b
U0007,U0007,0,62.20,1,12.83,1866,66,M,Current,Ta,Low grade,Yes,< 3 cm,No,High,1,Class 1
U0010,U0010,0,40.63,1,4.33,1219,76,M,Current,Ta,Low grade,No,< 3 cm,No,Intermediate,0,Class 2b
U0012,U0012,0,62.00,0,62.00,1860,83,F,Never,Ta,Low grade,No,< 3 cm,No,Intermediate,0,Class 2a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
U2116,U2116,0,161.13,1,13.30,4834,59,F,None,Ta,Low grade,No,< 3 cm,No,Intermediate,1,Class 3
U2117,U2117,0,27.00,1,6.30,810,61,M,None,Ta,Low grade,No,< 3 cm,Yes,Intermediate,1,Class 2a
U2118,U2118,0,141.00,1,4.17,4230,60,F,None,Ta,Low grade,No,< 3 cm,No,Intermediate,1,Class 2b
U2120,U2120,0,46.73,1,9.37,1402,52,F,None,Ta,Low grade,No,< 3 cm,No,Intermediate,1,Class 2a
U2122,U2122,1,11.57,1,4.83,347,78,M,None,Ta,Low grade,No,< 3 cm,No,Intermediate,1,Class 2b

# Read the expr csv file

In [8]:
# Don't use rpy2py if it's already converted or a NumPy array
expr = pd.read_csv('data/expr.csv', index_col=0)
expr

,B2M,CANX,HNRNPH1,RMRP,RPS17,RPS25,EEF1D,ADAM9,Sep.09,HSPA1B,...,KIR3DL1,CDY15P,VN1R88P,REXO1L9P,CYCSP12,KRT43P,RNU6.1226P,IGKV1OR.3,GYG2.AS1,LncRNA2747_ENSG00000256494
U0001,9.641292,8.294704,8.879183,10.957419,8.971963,8.899301,8.931035,8.692725,8.717858,7.364860,...,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143
U0002,10.969568,9.904651,8.532755,7.484596,9.110271,8.155065,7.806183,7.664232,7.677166,7.130855,...,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143
U0007,9.057950,8.428520,9.004439,9.982452,9.149469,8.800936,8.202923,8.508262,9.102715,7.077509,...,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143
U0010,10.840172,9.039196,8.884333,7.377476,7.615889,8.338603,8.887068,6.699793,8.596194,6.986257,...,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143
U0012,11.057663,9.747438,9.466948,8.741761,8.792949,8.571809,8.028207,7.927847,6.871401,7.783682,...,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
U2116,7.366015,8.533158,9.450972,8.469448,7.399753,7.728456,6.970599,7.312210,8.286791,8.719683,...,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143
U2117,9.657087,8.395514,8.957470,9.507080,6.718697,7.150315,6.613155,6.824384,7.356127,8.661348,...,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143
U2118,10.212921,8.273037,8.543611,8.127822,8.137967,8.194147,7.561886,7.938513,7.961356,8.067114,...,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143
U2120,8.348663,9.245114,8.912953,8.747625,8.086212,7.895971,7.359116,6.501322,8.046041,7.314658,...,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143
U2122,9.035957,7.982117,9.144469,8.205261,5.987195,5.434055,6.631945,5.579666,9.323664,7.514722,...,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143,-3.741143

In [9]:
expr.sum(axis=1)

U0001      183.613827
U0002    -5861.953095
U0007     6603.415566
U0010    13112.696385
U0012     4615.457472
             ...
U2116     5967.514077
U2117    -1441.593159
U2118      362.589452
U2120     6791.794673
U2122     8179.738951
Length: 286, dtype: float64

In [10]:
expr.var(axis=0).describe()

count    3.319700e+04
mean     1.287498e+00
std      1.326731e+00
min      1.979072e-31
25%      4.354971e-01
50%      9.219390e-01
75%      1.724032e+00
max      4.569769e+01
dtype: float64

In [12]:
expr.var(axis=0).sort_values()[-2000:]

FGF7P3                         3.259205
LncRNA6033_ENSG00000281706     3.259322
ZNF251                         3.260728
LncRNA3229_ENSG00000259692     3.261178
HOXC4                          3.261525
                                ...
LncRNA5967_ENSG00000280614    24.265166
LncRNA6003_ENSG00000281181    24.265573
LncRNA5978_ENSG00000280800    24.265657
RN7SL1                        28.667763
RN7SK                         45.697692
Length: 2000, dtype: float64